name: deploy

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
      
      - name: Download artifact
        id: download-artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: dotnet.yml
          workflow_conclusion: completed
          name: .net-app
          path: ~/myapp
    
      - name: Display structure of downloaded files
        run: ls -R
        working-directory: ~/myapp



      - name: IIS Deploy
  # You may pin to the exact commit or the version.
  # uses: ChristopheLav/iis-deploy@3b6a141da6e1923a4af25e01734ab58c081f8444
        uses: ChristopheLav/iis-deploy@v1.0.0
        with:
          # IIS website name
          website-name: ${{ secrets.MSDEPLOY_WEBSITE_NAME }}
          # MS Deploy Service URL
          msdeploy-service-url: ${{ secrets.MSDEPLOY_URL }}
          # Username used by Basic authentication to the MS Deploy Service
          msdeploy-username: ${{ secrets.SERVER_USERNAME }}
          # Password used by Basic authentication to the MS Deploy Service
          msdeploy-password: ${{ secrets.SERVER_PASSWORD }}
          # The path to the source directory that will be deployed
          source-path: ~/myapp
